# render.yaml - Production deployment configuration for Render.com
# OpenAI Voice Assistant v4.0.0

services:
  - type: web
    name: openai-voice-assistant
    env: python
    plan: starter # Можно изменить на professional для production
    
    # Команды сборки и запуска
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    
    # Health check
    healthCheckPath: /api/health
    
    # Переменные окружения
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Установите через Render Dashboard
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: "info"
    
    # Ресурсы
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    
    # Автоматический деплой
    autoDeploy: true
    
    # Регион (опционально)
    # region: oregon
