# render.yaml - ElevenLabs Voice Assistant с прямым WebSocket
services:
  # Основной веб-сервис
  - type: web
    name: elevenlabs-voice-assistant
    runtime: python3
    plan: starter
    
    # Команды сборки
    buildCommand: |
      pip install --upgrade pip && 
      pip install aiohttp fastapi uvicorn websockets colorlog python-dotenv
    
    # Команда запуска веб-версии
    startCommand: python main_render.py
    
    # Health check
    healthCheckPath: /health
    
    # Переменные окружения
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false  # Установите через Render Dashboard
      - key: PYTHON_VERSION
        value: "3.11"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PORT
        value: "10000"
