# render.yaml - ElevenLabs Conversational AI Deployment
# Конфигурация для деплоя на Render.com

services:
  - type: web
    name: elevenlabs-ai-assistant
    env: python
    plan: starter # Можете изменить на professional для production
    
    # Команды сборки и запуска
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    
    # Health check
    healthCheckPath: /api/health
    
    # Переменные окружения
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false  # ВАЖНО: Установите через Render Dashboard
      - key: ELEVENLABS_AGENT_ID
        sync: false  # Опционально: ID вашего агента
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: "info"
    
    # Ресурсы
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    
    # Автоматический деплой
    autoDeploy: true
    
    # Регион (опционально)
    # region: oregon

# ВАЖНЫЕ НАСТРОЙКИ:
# 1. Установите ELEVENLABS_API_KEY в Render Dashboard
# 2. Получите ключ на: https://elevenlabs.io/
# 3. ELEVENLABS_AGENT_ID - необязательный (для собственного агента)
# 4. Для публичного агента код будет работать с демо-агентом
