# render.yaml - ElevenLabs Voice Assistant с поддержкой аудио в браузере
services:
  # Основной веб-сервис
  - type: web
    name: elevenlabs-voice-assistant
    runtime: python3
    plan: starter
    
    # Команды сборки
    buildCommand: |
      pip install --upgrade pip && 
      pip install aiohttp fastapi uvicorn websockets colorlog python-dotenv
    
    # Команда запуска веб-версии
    startCommand: python main_render.py
    
    # Health check
    healthCheckPath: /health
    
    # Переменные окружения
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false  # Установите через Render Dashboard
      - key: ELEVENLABS_AGENT_ID
        value: "agent_01jzwcew2ferttga9m1zcn3js1"  # Можете заменить на свой ID
      - key: PYTHON_VERSION
        value: "3.11"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PORT
        value: "10000"
      - key: DEBUG
        value: "false"
    
    # Автоматический деплой
    autoDeploy: true
