# render.yaml - ElevenLabs Voice Assistant с прямым WebSocket
services:
  # Основной веб-сервис
  - type: web
    name: elevenlabs-voice-assistant
    runtime: python3
    plan: starter
    
    # Команды сборки
    buildCommand: |
      pip install --upgrade pip && 
      pip install aiohttp fastapi uvicorn websockets colorlog python-dotenv gunicorn
    
    # Команда запуска веб-версии - используем gunicorn как более стабильный вариант
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT main_render:app
    
    # Health check с более длинным таймаутом
    healthCheckPath: /health
    healthCheckTimeout: 60
    
    # Переменные окружения
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false  # Установите через Render Dashboard
      - key: PYTHON_VERSION
        value: "3.11"
      - key: LOG_LEVEL
        value: "INFO"
      # Порт должен определяться Render, а не быть фиксированным
      - key: PORT
        value: "10000"
