# render.yaml - ElevenLabs Conversational AI v2.0 Deployment
# Исправленная конфигурация для Render.com

services:
  - type: web
    name: elevenlabs-ai-assistant-v2
    env: python
    plan: starter # Можете изменить на professional для production
    
    # Команды сборки и запуска
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    
    # Health check
    healthCheckPath: /health
    
    # Переменные окружения
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false  # ВАЖНО: Установите через Render Dashboard
      - key: ELEVENLABS_AGENT_ID
        sync: false  # Опционально: ID вашего агента
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: "info"
    
    # Ресурсы
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    
    # Автоматический деплой
    autoDeploy: true
    
    # Регион (опционально)
    # region: oregon

# ===== ВАЖНЫЕ НАСТРОЙКИ ДЛЯ v2.0 =====
# 1. Установите ELEVENLABS_API_KEY в Render Dashboard
# 2. Получите ключ на: https://elevenlabs.io/
# 3. ELEVENLABS_AGENT_ID - необязательный (для собственного агента)
# 4. v2.0 исправляет проблемы с аудио воспроизведением
# 5. Поддерживает PCM формат и правильные WebSocket события

# ===== ИЗМЕНЕНИЯ В v2.0 =====
# - Исправлен формат аудио (PCM 16kHz)
# - Правильная обработка audio событий
# - Конвертация WebM в PCM base64
# - Ресэмплинг аудио до 16kHz
# - Улучшенная стабильность соединения
